### ISSUE TITLE
[INFO] File: /opt/deploy/assembly/assembly.xml does not exist.

### ISSUE THREAD

**Issue by testwill** [ldcsaa/hp-soa#1]
[ERROR] [3] [INFO] File: /opt/deploy/assembly/assembly.xml does not exist.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :hp-demo-bff-mysql

**Comment by ldcsaa** [comment]
There are 2 ways to deal with it:
1. Copy [assembly.xml](https://github.com/ldcsaa/hp-soa/blob/main/misc/opt/deploy/assembly/assembly.xml) to your `/opt/deploy/assembly` dir . 
2. Copy [assembly.xml](https://github.com/ldcsaa/hp-soa/blob/main/misc/opt/deploy/assembly/assembly.xml)  to any dir, and set `maven.assembly.descriptor` property in your `pom.xml` file to specify the assembly file location, like this:
```xml
<properties>
    <maven.assembly.descriptor>src/main/assembly/assembly.xml</maven.assembly.descriptor>
</properties>
```

**Comment by testwill** [comment]
好的，谢谢。我试下

**Comment by ldcsaa** [comment]
我会抽时间补充一下这个文档：[打包发布](https://github.com/ldcsaa/hp-soa/blob/main/misc/doc/deploy.md)

提供的assembly文件会打包 `/opt/deploy/scripts` 下的启动脚本，可以把 [启动脚本](https://github.com/ldcsaa/hp-soa/tree/main/misc/opt/deploy/scripts) 拷贝到 `/opt/deploy/scripts`目录。

**Comment by testwill** [comment]
这个文档会不会增加k8s部署

**Comment by ldcsaa** [comment]
> 这个文档会不会增加k8s部署

把程序包打包到docker镜像，k8s通过deployment启动这个镜像的容器即可。
后续可能会说明如何打包成docker镜像。

**Comment by testwill** [comment]
好的

**Comment by ldcsaa** [comment]
@testwill 1.1.2 / 1.0.10 版本已补上Docker 发布脚本和发布文档。https://github.com/ldcsaa/hp-soa/blob/main/misc/doc/deploy.md

**Comment by testwill** [comment]
谢谢
